tasks:
  - name: "prebuild"
    init: |
      ./install-sol.sh
      ./recover-config.sh
  - name: "validator"
    command: |
      if [[ ! "$PATH" =~ .*"solana/install/active_release/bin".* ]]; then
          eval $(gp env -e PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH");
      fi
      solana-test-validator
  - name: "main-terminal"
    command: |
      if [[ ! "$PATH" =~ .*"solana/install/active_release/bin".* ]]; then
          eval $(gp env -e PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH");
      fi
      solana --version
  - name: "mon"
    openMode: split-right
    command: |
      if [[ ! "$PATH" =~ .*"solana/install/active_release/bin".* ]]; then
          eval $(gp env -e PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH");
      fi
      npm run mon


github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: false

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - matklad.rust-analyzer
