tasks:
  - name: "prebuild"
    init: |
      ./install-sol.sh
      ./recover-config.sh
  - name: "validator"
    command: |
      solana-test-validator
  - name: "main-terminal"
    command: |
      solana --version
  - name: "mon"
    openMode: split-right
    command: |
      npm run mon


github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: false

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - matklad.rust-analyzer
