tasks:
  - name: "install"
    before: |
      sh install-sol.sh
  - name: "Command"
    command: |
      sh recover-config.sh

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - matklad.rust-analyzer
