tasks:
  - name: "install"
    before: |
      ./install-sol.sh
  - name: "Command"
    init: |
      ./recover-config.sh

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - matklad.rust-analyzer
